import React, {useEffect,useState} from 'react';
type Call=(path:string,opts?:RequestInit,token?:string)=>Promise<any>;
type Props={request:Call;token:string;message:(m:string)=>void};
const json=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
export function BuildTogether({request,token,message}:Props){
 const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!token){message('Sign in or create an account to record your interest.');return;}const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{const r=await request('/api/partnerships/interest',json({kind:f.get('kind'),organization:f.get('organization'),message:f.get('message')}),token);message(r.message);form.reset()}catch(err){message(String(err))}finally{setBusy(false)}}
 return <section className="section"><span className="eyebrow">BUILD FIXMYAREA WITH US</span><h1>Turn visible problems into measurable improvements.</h1><p>FixMyArea is an early pilot seeking contributors, participating organizations and conversations with potential investment partners. Participation and funding are subject to review.</p><div className="grid three">{[['Contribute expertise','Help with software engineering, GIS, accessibility, security and community research.'],['Run a local pilot','Assemblies, utilities and sanitation teams can test reporting and resolution in a defined service area.'],['Support verified needs','NGOs and CSR teams can discuss interventions and evidence of community outcomes.']].map(([title,copy])=><article className="card" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="grid two"><article className="panel"><h2>Development roadmap</h2><p>Available: photo reports, issue maps, tracking, repair confirmation, routing suggestions and inspection notes.</p><p>Next: external messaging, offline photo capture, AI classification and independent pilot evaluation.</p><a href="https://github.com/kwaw-ebn/FIXMYAREA" target="_blank" rel="noreferrer">Explore the code and contribution guide →</a></article><form className="panel" onSubmit={submit}><h2>Express your interest</h2><p>Your enquiry is private and reviewed by a platform administrator. This form records interest; it does not send email or accept payments.</p><label>I would like to<select name="kind">{['Contributor','Pilot organization','NGO / CSR','Investment discussion'].map(k=><option key={k}>{k}</option>)}</select></label><label>Organization (optional)<input name="organization" maxLength={150}/></label><label>How would you like to help?<textarea name="message" required minLength={20} maxLength={2000}/></label><button className="primary" disabled={busy||!token}>{busy?'Saving…':token?'Record my interest':'Sign in to express interest'}</button></form></div></section>
}
export function Confirmation({request,token,message,report,refresh}:Props&{report:any;refresh:()=>Promise<void>}){
 const [can,setCan]=useState(false);const [busy,setBusy]=useState(false);
 useEffect(()=>{setCan(false);if(token)request(`/api/reports/${report.id}/confirmation`,{},token).then(r=>setCan(r.can_confirm)).catch(()=>{})},[report.id,report.status,token]);
 async function confirm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await request(`/api/reports/${report.id}/confirmation`,json({resolved:f.get('resolved')==='yes',note:f.get('note')}),token);await refresh();message('Your repair feedback has been recorded.')}catch(err){message(String(err))}finally{setBusy(false)}}
 return can?<form className="panel" onSubmit={confirm}><h2>Does the repair appear complete?</h2><p>As the original reporter, you can confirm the repair or reopen the issue for further work.</p><label>Your assessment<select name="resolved"><option value="yes">Yes, the issue appears resolved</option><option value="no">No, reopen this issue</option></select></label><label>Feedback (required when reopening)<textarea name="note" maxLength={1000}/></label><button className="primary" disabled={busy}>Submit repair feedback</button></form>:null
}
export function Workspace({request,token,message,open}:Props&{open:(r:any)=>void}){
 const [data,setData]=useState<any>(null),[queue,setQueue]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]);
 const load=()=>Promise.all([request('/api/organization/analytics',{},token),request('/api/organization/review-queue',{},token),request('/api/organization/routing-rules',{},token)]).then(([d,q,r])=>{setData(d);setQueue(q);setRules(r)}).catch(e=>message(String(e)));
 useEffect(()=>{load()},[token]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await request('/api/organization/routing-rules',json({category:f.get('category'),community:f.get('community'),target_days:Number(f.get('target_days'))}),token);message(r.message);await load()}catch(err){message(String(err))}}
 return <><div className="numbers embedded">{[['Resolution rate',data?`${data.resolution_rate}%`:'—'],['Overdue',data?.overdue??'—'],['Average repair days',data?.average_resolution_days??'—']].map(([label,value])=><div key={String(label)}><strong>{value}</strong><span>{label}</span></div>)}</div><p>Overdue cases use configured community/category targets, or a 14 day pilot default. Timing starts at submission.</p><h2>Review queue</h2><p>Verified service area matches awaiting human assignment.</p>{queue.length?queue.map(r=><button className="reportcard" key={r.id} onClick={()=>open(r)}>{r.tracking} · {r.category} · {r.community}</button>):<p>No matching unassigned reports.</p>}<form className="panel" onSubmit={save}><h3>Community routing and response target</h3><p>Organization administrators and supervisors can configure exact community names. Platform verification activates routing suggestions.</p><label>Category<select name="category">{['Road/Pothole','Drainage','Waste/Sanitation','Streetlight','Water','Flooding','Public Facility','Road Safety','Environmental Hazard','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label>Community<input name="community" minLength={2} maxLength={120} required/></label><label>Target days<input name="target_days" type="number" min={1} max={365} defaultValue={14} required/></label><button className="primary">Save rule</button></form><ul>{rules.map(r=><li key={r.id}>{r.category} · {r.community} · {r.target_days} days</li>)}</ul></>
}
export function Routing({request,token,message,report}:Props&{report:any}){const [data,setData]=useState<any>(null);useEffect(()=>{request(`/api/reports/${report.id}/routing`,{},token).then(setData).catch(()=>setData(null))},[report.id,token]);return data?<article className="panel"><h3>Responsibility review</h3><p>{data.requires_review?'Responsibility needs review. No automatic assignment has been made.':'One verified service area matches. An officer must confirm assignment.'}</p>{data.suggestions.map((s:any)=><p key={s.organization_id}><strong>{s.name}</strong> · {s.reason} · target {s.target_days} days</p>)}</article>:null}
export function FieldNotes({request,token,message,report}:Props&{report:any}){
 const [account,setAccount]=useState(''); const key='fma_visits_'+account;const [count,setCount]=useState(0);
 useEffect(()=>{request('/api/me',{},token).then(u=>setAccount(u.id)).catch(()=>{})},[token]);
 const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}};
 async function sync(){if(!account||!navigator.onLine)return;let items=read();for(const item of [...items]){try{await request('/api/field/visits',json(item),token);items=items.filter((x:any)=>x.id!==item.id);localStorage.setItem(key,JSON.stringify(items))}catch(err){message('Inspection sync needs attention: '+String(err));break}}setCount(items.length)}
 useEffect(()=>{setCount(read().length);sync();window.addEventListener('online',sync);return()=>window.removeEventListener('online',sync)},[token,account]);
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!account){message('Connect once to load your account before saving notes.');return;}const form=e.currentTarget;const note=String(new FormData(form).get('note')||'').trim();if(note.length<5)return;try{const items=read();items.push({id:crypto.randomUUID(),report_id:report.id,note});localStorage.setItem(key,JSON.stringify(items));setCount(items.length);form.reset();message('Inspection note saved on this device.');sync()}catch{message('Device storage unavailable. Reconnect before recording your inspection.')}}
 return <form className="panel" onSubmit={save}><h3>Field inspection note</h3><p>Notes remain internal. Pending notes stay on this device and synchronize when online. Photo and status changes still require connectivity. Use a trusted device.</p><label>Inspection findings<textarea name="note" minLength={5} maxLength={1000} required/></label><button className="primary">Save inspection note</button><small>{count} pending synchronization</small><button type="button" className="secondary" onClick={sync}>Synchronize now</button></form>
}
export function Hotspots({request}:Pick<Props,'request'>){const [cells,setCells]=useState<any[]>([]);useEffect(()=>{request('/api/analytics/hotspots').then(setCells).catch(()=>{})},[]);return <article className="panel"><h2>Recurring issue clusters</h2><p>Approximate map cells with at least three unresolved reports of the same category. These are reporting patterns, not verified infrastructure risk predictions.</p>{cells.length?<ul>{cells.map((c,i)=><li key={i}>{c.category}: {c.count} reports near {c.latitude.toFixed(2)}, {c.longitude.toFixed(2)}</li>)}</ul>:<p>Not enough reports to identify clusters yet.</p>}</article>}
export function PlatformOps({request,token,message}:Props){const [interests,setInterests]=useState<any[]>([]),[orgs,setOrgs]=useState<any[]>([]);useEffect(()=>{request('/api/partnerships/interest',{},token).then(setInterests).catch(e=>message(String(e)));request('/api/organizations').then(setOrgs)},[token]);async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await request(`/api/organizations/${f.get('organization_id')}/verification`,json({verified:f.get('verified')==='yes'}),token);message('Organization verification updated.')}catch(err){message(String(err))}}return <><h2>Platform administration</h2><form className="panel" onSubmit={verify}><h3>Organization verification</h3><p>Confirm the organization identity and service responsibility independently before approving it.</p><label>Organization<select name="organization_id" required>{orgs.map(o=><option key={o.id} value={o.id}>{o.name} · {o.district}</option>)}</select></label><label>Decision<select name="verified"><option value="no">Not verified</option><option value="yes">Verified</option></select></label><button className="primary" disabled={!orgs.length}>Save verification</button></form><h3>Private partner enquiries</h3>{interests.map(i=><article className="panel" key={i.id}><strong>{i.kind} · {i.organization||'Individual'}</strong><p>{i.message}</p><p>{i.email} · {new Date(i.at).toLocaleDateString()}</p></article>)}{!interests.length&&<p>No enquiries recorded yet.</p>}</>}
export function AssignmentPanel({request,token,message,report,organizations,refresh}:Props&{report:any;organizations:any[];refresh:()=>Promise<void>}){const [people,setPeople]=useState<any[]>([]),[org,setOrg]=useState(report.organization_id||organizations[0]?.id||'');useEffect(()=>{request('/api/organization/staff',{},token).then(setPeople).catch(()=>{})},[token]);async function assign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await request(`/api/reports/${report.id}/assign`,json({organization_id:org,assignee_id:f.get('assignee_id')||null}),token);await refresh();message('Assignment saved.')}catch(err){message(String(err))}}return <form className="panel" onSubmit={assign}><h3>Assign responsibility</h3><label>Organization<select value={org} onChange={e=>setOrg(e.target.value)} required>{organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Field officer<select name="assignee_id" key={org}><option value="">Organization queue</option>{people.filter(p=>p.organization_id===org).map(p=><option key={p.id} value={p.id}>{p.email} · {p.role}</option>)}</select></label><button className="primary" disabled={!org}>Assign</button></form>}
