import React, {useEffect,useState} from 'react';
import {MapContainer,TileLayer,CircleMarker,Popup} from 'react-leaflet';
type Call=(path:string,opts?:RequestInit,token?:string)=>Promise<any>;
type Props={request:Call;token:string;message:(m:string)=>void};
const json=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
export function Confirmation({request,token,message,report,refresh}:Props&{report:any;refresh:()=>Promise<void>}){
 const [can,setCan]=useState(false);const [busy,setBusy]=useState(false);
 useEffect(()=>{setCan(false);if(token)request(`/api/reports/${report.id}/confirmation`,{},token).then(r=>setCan(r.can_confirm)).catch(()=>{})},[report.id,report.status,token]);
 async function confirm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await request(`/api/reports/${report.id}/confirmation`,json({resolved:f.get('resolved')==='yes',note:f.get('note')}),token);await refresh();message('Your repair feedback has been recorded.')}catch(err){message(String(err))}finally{setBusy(false)}}
 return can?<form className="panel" onSubmit={confirm}><h2>Does the repair appear complete?</h2><p>As the original reporter, you can confirm the repair or reopen the issue for further work.</p><label>Your assessment<select name="resolved"><option value="yes">Yes, the issue appears resolved</option><option value="no">No, reopen this issue</option></select></label><label>Feedback (required when reopening)<textarea name="note" maxLength={1000}/></label><button className="primary" disabled={busy}>Submit repair feedback</button></form>:null
}
export function Workspace({request,token,message,open}:Props&{open:(r:any)=>void}){
 const [data,setData]=useState<any>(null),[queue,setQueue]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[overdue,setOverdue]=useState<any[]>([]);
 const load=()=>Promise.all([request('/api/organization/analytics',{},token),request('/api/organization/review-queue',{},token),request('/api/organization/routing-rules',{},token),request('/api/organization/overdue',{},token)]).then(([d,q,r,o])=>{setData(d);setQueue(q);setRules(r);setOverdue(o)}).catch(e=>message(String(e)));
 useEffect(()=>{load();request('/api/organization/check-alerts',{method:'POST'},token).catch(e=>message(String(e)))},[token]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await request('/api/organization/routing-rules',json({category:f.get('category'),community:f.get('community'),target_days:Number(f.get('target_days'))}),token);message(r.message);await load()}catch(err){message(String(err))}}
 return <><div className="numbers embedded">{[['Resolution rate',data?`${data.resolution_rate}%`:'—'],['Overdue',data?.overdue??'—'],['Average repair days',data?.average_resolution_days??'—']].map(([label,value])=><div key={String(label)}><strong>{value}</strong><span>{label}</span></div>)}</div><p>Overdue cases use configured community/category targets, or a 14 day pilot default. Timing starts at submission.</p><h2>Overdue cases needing attention</h2><p>Alerts are checked when you open Workspace. Each missed target produces one in-app alert per staff account.</p><button className="secondary" onClick={()=>{load();request('/api/organization/check-alerts',{method:'POST'},token).then(r=>message(`${r.created} new overdue alerts`)).catch(e=>message(String(e)))}}>Refresh overdue alerts</button>{overdue.map(r=><button className="reportcard" key={r.id} onClick={()=>open(r)}>{r.tracking} · {r.community} · due {new Date(r.due_at).toLocaleDateString()}</button>)}{!overdue.length&&<p>No overdue cases.</p>}<h2>Review queue</h2><p>Verified service area matches awaiting human assignment.</p>{queue.length?queue.map(r=><button className="reportcard" key={r.id} onClick={()=>open(r)}>{r.tracking} · {r.category} · {r.community}</button>):<p>No matching unassigned reports.</p>}<form className="panel" onSubmit={save}><h3>Community routing and response target</h3><p>Organization administrators and supervisors can configure exact community names. Platform verification activates routing suggestions.</p><label>Category<select name="category">{['Road/Pothole','Drainage','Waste/Sanitation','Streetlight','Water','Flooding','Public Facility','Road Safety','Environmental Hazard','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label>Community<input name="community" minLength={2} maxLength={120} required/></label><label>Target days<input name="target_days" type="number" min={1} max={365} defaultValue={14} required/></label><button className="primary">Save rule</button></form><ul>{rules.map(r=><li key={r.id}>{r.category} · {r.community} · {r.target_days} days</li>)}</ul></>
}
export function Routing({request,token,message,report}:Props&{report:any}){const [data,setData]=useState<any>(null);useEffect(()=>{request(`/api/reports/${report.id}/routing`,{},token).then(setData).catch(()=>setData(null))},[report.id,token]);return data?<article className="panel"><h3>Responsibility review</h3><p>{data.requires_review?'Responsibility needs review. No automatic assignment has been made.':'One verified service area matches. An officer must confirm assignment.'}</p>{data.suggestions.map((s:any)=><p key={s.organization_id}><strong>{s.name}</strong> · {s.reason} · target {s.target_days} days</p>)}</article>:null}
export function FieldNotes({request,token,message,report}:Props&{report:any}){
 const [account,setAccount]=useState(''); const key='fma_visits_'+account;const [count,setCount]=useState(0);
 useEffect(()=>{request('/api/me',{},token).then(u=>setAccount(u.id)).catch(()=>{})},[token]);
 const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}};
 async function sync(){if(!account||!navigator.onLine)return;let items=read();for(const item of [...items]){try{await request('/api/field/visits',json(item),token);items=items.filter((x:any)=>x.id!==item.id);localStorage.setItem(key,JSON.stringify(items))}catch(err){message('Inspection sync needs attention: '+String(err));break}}setCount(items.length)}
 useEffect(()=>{setCount(read().length);sync();window.addEventListener('online',sync);return()=>window.removeEventListener('online',sync)},[token,account]);
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!account){message('Connect once to load your account before saving notes.');return;}const form=e.currentTarget;const note=String(new FormData(form).get('note')||'').trim();if(note.length<5)return;try{const items=read();items.push({id:crypto.randomUUID(),report_id:report.id,note});localStorage.setItem(key,JSON.stringify(items));setCount(items.length);form.reset();message('Inspection note saved on this device.');sync()}catch{message('Device storage unavailable. Reconnect before recording your inspection.')}}
 return <form className="panel" onSubmit={save}><h3>Field inspection note</h3><p>Notes remain internal. Pending notes stay on this device and synchronize when online. Use Save field inspection below to queue photos. Status changes require connectivity. Use a trusted device.</p><label>Inspection findings<textarea name="note" minLength={5} maxLength={1000} required/></label><button className="primary">Save inspection note</button><small>{count} pending synchronization</small><button type="button" className="secondary" onClick={sync}>Synchronize now</button></form>
}
export function Hotspots({request}:Pick<Props,'request'>){const [cells,setCells]=useState<any[]>([]),[category,setCategory]=useState('All'),[error,setError]=useState('');useEffect(()=>{request('/api/analytics/hotspots').then(setCells).catch(()=>setError('Hotspot data unavailable. Try again when connected.'))},[]);const visible=cells.filter(c=>category==='All'||c.category===category);return <article className="panel"><h2>Recurring issue hotspot map</h2><p>Approximate cells with at least three unresolved reports of the same category. These are reporting patterns, not verified infrastructure risk predictions.</p><label>Hotspot category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{[...new Set(cells.map(c=>c.category))].map(c=><option key={c}>{c}</option>)}</select></label><div className="miniMap"><MapContainer center={[5.6,-0.187]} zoom={7} style={{height:'100%',width:'100%'}}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{visible.map((c,i)=><CircleMarker key={i} center={[c.latitude,c.longitude]} radius={Math.min(30,8+c.count*2)} pathOptions={{color:'#b45309',fillOpacity:0.5}}><Popup>{c.category} · {c.count} unresolved reports</Popup></CircleMarker>)}</MapContainer></div>{error?<p role="status">{error}</p>:visible.length?<ul>{visible.map((c,i)=><li key={i}>{c.category}: {c.count} reports near {c.latitude.toFixed(2)}, {c.longitude.toFixed(2)}</li>)}</ul>:<p>Not enough reports to identify clusters for this category yet.</p>}</article>}
export function MessagingAvailability({request,token}:Pick<Props,'request'|'token'>){const [loaded,setLoaded]=useState(false);useEffect(()=>{request('/api/notification-preferences',{},token).then(()=>setLoaded(true)).catch(()=>setLoaded(false))},[token]);return <article className="panel"><h2>Progress update channels</h2><p>{loaded?'In-app updates are available.':'Connect to check notification availability.'}</p><p>SMS and WhatsApp updates are awaiting provider setup and account approval. No messages are being sent through these channels.</p></article>}
export function PlatformOps({request,token,message}:Props){const [interests,setInterests]=useState<any[]>([]),[orgs,setOrgs]=useState<any[]>([]);useEffect(()=>{request('/api/partnerships/interest',{},token).then(setInterests).catch(e=>message(String(e)));request('/api/organizations').then(setOrgs)},[token]);async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await request(`/api/organizations/${f.get('organization_id')}/verification`,json({verified:f.get('verified')==='yes'}),token);message('Organization verification updated.')}catch(err){message(String(err))}}return <><h2>Platform administration</h2><form className="panel" onSubmit={verify}><h3>Organization verification</h3><p>Confirm the organization identity and service responsibility independently before approving it.</p><label>Organization<select name="organization_id" required>{orgs.map(o=><option key={o.id} value={o.id}>{o.name} · {o.district}</option>)}</select></label><label>Decision<select name="verified"><option value="no">Not verified</option><option value="yes">Verified</option></select></label><button className="primary" disabled={!orgs.length}>Save verification</button></form><h3>Private partner enquiries</h3>{interests.map(i=><article className="panel" key={i.id}><strong>{i.kind} · {i.organization||'Individual'}</strong><p>{i.message}</p><p>{i.email} · {new Date(i.at).toLocaleDateString()}</p></article>)}{!interests.length&&<p>No enquiries recorded yet.</p>}</>}
export function AssignmentPanel({request,token,message,report,organizations,refresh}:Props&{report:any;organizations:any[];refresh:()=>Promise<void>}){const [people,setPeople]=useState<any[]>([]),[org,setOrg]=useState(report.organization_id||organizations[0]?.id||'');useEffect(()=>{request('/api/organization/staff',{},token).then(setPeople).catch(()=>{})},[token]);async function assign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await request(`/api/reports/${report.id}/assign`,json({organization_id:org,assignee_id:f.get('assignee_id')||null}),token);await refresh();message('Assignment saved.')}catch(err){message(String(err))}}return <form className="panel" onSubmit={assign}><h3>Assign responsibility</h3><label>Organization<select value={org} onChange={e=>setOrg(e.target.value)} required>{organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Field officer<select name="assignee_id" key={org}><option value="">Organization queue</option>{people.filter(p=>p.organization_id===org).map(p=><option key={p.id} value={p.id}>{p.email} · {p.role}</option>)}</select></label><button className="primary" disabled={!org}>Assign</button></form>}
