import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapContainer, TileLayer, Marker, Popup, useMapEvents} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';
import './style.css';

const API = import.meta.env.VITE_API_HOST ? `https://${import.meta.env.VITE_API_HOST}` : 'http://localhost:8000';
const categories=['Road/Pothole','Drainage','Waste/Sanitation','Streetlight','Water','Flooding','Public Facility','Road Safety','Environmental Hazard','Other'];
type Report={id:string;tracking:string;category:string;description:string;community:string;latitude:number;longitude:number;status:string;created_at:string;support_count:number;images:{id:string;kind:string}[];timeline?:{action:string;note:string;at:string}[]};
type Stats={reported:number;resolved:number;communities:number;organizations:number;by_status:Record<string,number>};
const icon=new L.Icon({iconUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',shadowUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',iconSize:[25,41],iconAnchor:[12,41]});
async function request(path:string,opts:RequestInit={},token='') {const res=await fetch(API+path,{...opts,headers:{...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||'Request failed');return data;}
function Pin({setPoint}:{setPoint:(p:[number,number])=>void}){useMapEvents({click(e){setPoint([e.latlng.lat,e.latlng.lng])}});return null;}
function App(){
 const [page,setPage]=useState('home'),[token,setToken]=useState(localStorage.getItem('fma_token')||''),[role,setRole]=useState(localStorage.getItem('fma_role')||''),[reports,setReports]=useState<Report[]>([]),[stats,setStats]=useState<Stats|null>(null),[selected,setSelected]=useState<Report|null>(null),[message,setMessage]=useState(''),[category,setCategory]=useState(categories[0]),[mapCategory,setMapCategory]=useState('All'),[point,setPoint]=useState<[number,number]>([5.6037,-0.1870]),[duplicates,setDuplicates]=useState<Report[]>([]),[photo,setPhoto]=useState<File|null>(null),[mine,setMine]=useState<Report[]>([]),[notices,setNotices]=useState<{message:string;at:string}[]>([]),[orgs,setOrgs]=useState<{id:string;name:string}[]>([]);
 const refresh=async()=>{try{const [r,s,o]=await Promise.all([request('/api/reports'),request('/api/analytics'),request('/api/organizations')]);setReports(r);setStats(s);setOrgs(o);}catch(e){setMessage(String(e))}};
 useEffect(()=>{refresh();const match=location.pathname.match(/^\/report\/(FMA-[A-Za-z0-9-]+)$/);if(match)request('/api/reports/'+match[1]).then((r:Report)=>{setSelected(r);setPage('detail')}).catch(()=>{})},[]);
 useEffect(()=>{if(token){request('/api/reports/mine',{},token).then(setMine).catch(()=>{});request('/api/notifications',{},token).then(setNotices).catch(()=>{})}},[token,page]);
 useEffect(()=>{if(page==='report')request(`/api/duplicates?category=${encodeURIComponent(category)}&latitude=${point[0]}&longitude=${point[1]}`).then(setDuplicates).catch(()=>{})},[category,point,page]);
 const navigate=(p:string)=>{history.replaceState(null,'','/');setPage(p);setMessage('');window.scrollTo(0,0)};
 async function auth(e:React.FormEvent<HTMLFormElement>,mode:string){e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await request(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});if(mode==='register'){setMessage('Account created. Sign in now.');return}localStorage.setItem('fma_token',data.access_token);localStorage.setItem('fma_role',data.role);setToken(data.access_token);setRole(data.role);navigate('mine')}catch(err){setMessage(String(err))}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!photo){setMessage('Add a photo of the issue.');return}const form=new FormData(e.currentTarget);form.set('latitude',String(point[0]));form.set('longitude',String(point[1]));form.set('category',category);form.set('photo',photo);try{const r=await request('/api/reports',{method:'POST',body:form},token);setPhoto(null);await refresh();setMessage(`Submitted: ${r.tracking}`);navigate('mine');setMessage(`Submitted: ${r.tracking}`)}catch(err){setMessage(String(err))}}
 async function open(r:Report){try{setSelected(await request('/api/reports/'+r.id));history.replaceState(null,'',`/report/${r.tracking}`);setPage('detail');window.scrollTo(0,0)}catch(err){setMessage(String(err))}}
 async function support(r:Report){if(!token){navigate('login');return}try{await request(`/api/reports/${r.id}/support`,{method:'POST'},token);await refresh();setMessage('You support this report.')}catch(err){setMessage(String(err))}}
 async function change(e:React.FormEvent<HTMLFormElement>,kind:'assign'|'status'|'resolution'){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);try{let body:BodyInit;let headers:HeadersInit={};if(kind==='resolution')body=f;else{body=JSON.stringify(kind==='assign'?{organization_id:f.get('organization_id')}:{status:f.get('status'),note:f.get('note')});headers={'Content-Type':'application/json'}}await request(`/api/reports/${selected.id}/${kind}`,{method:'POST',body,headers},token);setSelected(await request('/api/reports/'+selected.id));await refresh();setMessage('Update saved.')}catch(err){setMessage(String(err))}}
 function locate(){navigator.geolocation?.getCurrentPosition(p=>setPoint([p.coords.latitude,p.coords.longitude]),()=>setMessage('Location unavailable. Tap the map to place the pin.'),{enableHighAccuracy:true,timeout:10000})}
 const staff=['officer','supervisor','org_admin','platform_admin'].includes(role);
 return <><header><button className="brand" onClick={()=>navigate('home')}><span className="brandmark">⌖</span> FixMyArea</button><nav><button onClick={()=>navigate('map')}>Community map</button><button onClick={()=>navigate('impact')}>Impact</button>{token&&<button onClick={()=>navigate('mine')}>My reports</button>}{staff&&<button onClick={()=>navigate('dashboard')}>Workspace</button>}{token?<button onClick={()=>{localStorage.removeItem('fma_token');localStorage.removeItem('fma_role');setToken('');setRole('');navigate('home')}}>Sign out</button>:<button onClick={()=>navigate('login')}>Sign in</button>}<button className="navcta" onClick={()=>navigate(token?'report':'register')}>Report an issue</button></nav></header>
 <main>{message&&<div className="notice" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss">×</button></div>}
 {page==='home'&&<><section className="hero"><div><div className="eyebrow">A better way to care for our communities</div><h1>See a problem in your community? <em>Report it.</em></h1><p>FixMyArea helps communities report local infrastructure problems, track progress and see when action is taken.</p><div className="actions"><button className="primary" onClick={()=>navigate(token?'report':'register')}>Report an Issue →</button><button className="secondary" onClick={()=>navigate('map')}>Explore Community Map</button></div><div className="trust">Photo + location &nbsp;·&nbsp; Clear tracking &nbsp;·&nbsp; Public progress</div></div><div className="heroart"><div className="arttop">COMMUNITY ISSUE TRACKER <span>● LIVE</span></div><div className="artmap"><span>📍</span><span>📍</span><span>📍</span></div><div className="artcard"><strong>Road hazard reported</strong><small>Community issue · Tracking available</small><div className="progress"><i/></div><small>Submitted → Review → Action → Resolved</small></div></div></section><section className="numbers">{[['Issues reported',stats?.reported],['Issues resolved',stats?.resolved],['Communities',stats?.communities],['Organizations',stats?.organizations]].map(([label,value])=><div key={String(label)}><strong>{value??'—'}</strong><span>{label}</span></div>)}</section><section className="section"><span className="eyebrow">HOW IT WORKS</span><h2>From a local problem to visible progress.</h2><div className="grid three">{[['01','Report','Take a photo, add your location and describe the issue.'],['02','Track','Use your tracking number to follow each status update.'],['03','See action','View resolution evidence and community impact.']].map(([n,title,desc])=><article className="card" key={n}><span className="step">{n}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></section><section className="section light"><span className="eyebrow">EXPLORE YOUR AREA</span><h2>Every report has a place on the map.</h2><p>See public issues nearby and support an existing report.</p><button className="primary" onClick={()=>navigate('map')}>Open community map →</button></section><section className="section"><span className="eyebrow">RECENT ACTIVITY</span><h2>Community reports</h2>{reports.length?<div className="grid three">{reports.slice(0,3).map(r=><ReportCard key={r.id} r={r} open={open}/>)}</div>:<p>No public reports yet. Be the first to report an issue.</p>}</section><section className="section dark"><h2>Make community problems visible.</h2><p>Organizations and partners can use verified reports to coordinate action and measure results.</p><button className="primary" onClick={()=>navigate(token?'report':'register')}>Get started →</button></section></>}
 {page==='register'||page==='login'?<section className="narrow"><span className="eyebrow">YOUR COMMUNITY STARTS HERE</span><h1>{page==='register'?'Create your account':'Welcome back'}</h1><form onSubmit={e=>auth(e,page)} className="panel"><label>Email<input type="email" name="email" required autoComplete="email"/></label><label>Password<input type="password" name="password" minLength={10} required autoComplete={page==='login'?'current-password':'new-password'}/></label><button className="primary" type="submit">{page==='register'?'Create account':'Sign in'}</button></form><p>{page==='register'?'Already registered?':'New here?'} <button className="link" onClick={()=>navigate(page==='register'?'login':'register')}>{page==='register'?'Sign in':'Create account'}</button></p></section>:null}
 {page==='report'&&<section className="narrow"><span className="eyebrow">REPORT AN ISSUE</span><h1>Help us see what needs attention.</h1><p>Choose a public issue, add a photo and place a pin at the issue location.</p><form onSubmit={submit} className="panel"><label>Issue category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Photo of the issue<input type="file" accept="image/*" capture="environment" onChange={e=>setPhoto(e.target.files?.[0]||null)} required/></label><label>Community or nearby landmark<input name="community" required minLength={2} maxLength={120} placeholder="e.g. Agona Swedru market road"/></label><label>What is happening?<textarea name="description" required minLength={5} maxLength={1000} rows={4} placeholder="Describe the issue in a few words"/></label><div><strong>Issue location</strong><p>Tap the map to adjust the pin. This location appears on the public map.</p><button type="button" className="secondary" onClick={locate}>Use my current location</button><div className="miniMap"><MapContainer center={point} zoom={13} style={{height:'100%',width:'100%'}}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Pin setPoint={setPoint}/><Marker position={point} icon={icon}/></MapContainer></div><small>Pin: {point[0].toFixed(5)}, {point[1].toFixed(5)}</small></div>{duplicates.length>0&&<div className="duplicates"><strong>This issue may already have been reported.</strong><p>Support an existing report if it describes the same problem.</p>{duplicates.map(r=><button type="button" key={r.id} onClick={()=>support(r)}>{r.tracking} · {r.community} · Support existing report</button>)}</div>}<button className="primary" type="submit">Submit report →</button></form></section>}
 {page==='map'&&<section className="section"><span className="eyebrow">COMMUNITY MAP</span><h1>See what is happening nearby.</h1><div className="filters"><select value={mapCategory} onChange={e=>setMapCategory(e.target.value)}><option value="All">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><span>{reports.length} public reports</span></div><div className="bigMap"><MapContainer center={[5.6037,-0.187]} zoom={7} style={{height:'100%',width:'100%'}}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{reports.filter(r=>mapCategory==='All'||r.category===mapCategory).map(r=><Marker key={r.id} position={[r.latitude,r.longitude]} icon={icon}><Popup><strong>{r.category}</strong><br/>{r.community}<br/>{r.status}<br/><button onClick={()=>open(r)}>View report</button></Popup></Marker>)}</MapContainer></div><div className="grid three">{reports.filter(r=>mapCategory==='All'||r.category===mapCategory).map(r=><ReportCard key={r.id} r={r} open={open}/>)}</div></section>}
 {page==='detail'&&selected&&<section className="section detail"><button className="link" onClick={()=>navigate('map')}>← Back to map</button><span className="eyebrow">{selected.tracking}</span><h1>{selected.category} in {selected.community}</h1><span className="badge">{selected.status}</span><p>{selected.description}</p><p>Reported {new Date(selected.created_at).toLocaleDateString()} · Supported by {selected.support_count} residents</p><div className="actions"><button className="secondary" onClick={()=>support(selected)}>Support this report</button><button className="secondary" onClick={()=>navigator.clipboard.writeText(location.href)}>Copy page link</button></div><div className="grid two">{selected.images.map(im=><figure key={im.id}><img src={`${API}/api/images/${im.id}`} alt={`${im.kind} evidence for ${selected.tracking}`}/><figcaption>{im.kind==='before'?'Reported issue':'After work'}</figcaption></figure>)}</div><h2>Progress timeline</h2><ol className="timeline">{selected.timeline?.map((ev,i)=><li key={i}><strong>{ev.action}</strong> · {new Date(ev.at).toLocaleString()}<p>{ev.note}</p></li>)}</ol>{staff&&<div className="grid two"><form className="panel" onSubmit={e=>change(e,'assign')}><h3>Assign organization</h3><select name="organization_id" required>{orgs.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select><button className="primary">Assign</button></form><form className="panel" onSubmit={e=>change(e,'status')}><h3>Update status</h3><select name="status">{['Under Review','Verified','Assigned','In Progress','Resolved','Closed'].map(s=><option key={s}>{s}</option>)}</select><textarea name="note" placeholder="Public progress note"/><button className="primary">Save status</button></form><form className="panel" onSubmit={e=>change(e,'resolution')}><h3>Upload after evidence</h3><input type="file" accept="image/*" name="photo" required/><textarea name="note" placeholder="Work completed"/><button className="primary">Upload evidence</button></form></div>}</section>}
 {page==='mine'&&<section className="section"><span className="eyebrow">MY FIXMYAREA</span><h1>Your reports</h1><button className="primary" onClick={()=>navigate('report')}>Report an issue →</button><div className="grid three">{mine.map(r=><ReportCard key={r.id} r={r} open={open}/>)}</div>{!mine.length&&<p>You have not submitted a report yet.</p>}<h2>Updates</h2>{notices.map((n,i)=><p className="update" key={i}>{n.message} · {new Date(n.at).toLocaleDateString()}</p>)}</section>}
 {page==='dashboard'&&<section className="section"><span className="eyebrow">ORGANIZATION WORKSPACE</span><h1>Reports and progress</h1><div className="numbers embedded">{Object.entries(stats?.by_status||{}).map(([s,n])=><div key={s}><strong>{n}</strong><span>{s}</span></div>)}</div><p>Reports assigned to your organization</p><div className="grid three"><DashboardReports token={token} open={open}/></div></section>}
 {page==='impact'&&<section className="section"><span className="eyebrow">COMMUNITY IMPACT</span><h1>Visible reports. Measurable action.</h1><div className="numbers embedded">{[['Reports',stats?.reported],['Resolved',stats?.resolved],['Communities',stats?.communities],['Organizations',stats?.organizations]].map(([label,n])=><div key={String(label)}><strong>{n??0}</strong><span>{label}</span></div>)}</div><h2>Recently resolved</h2><div className="grid three">{reports.filter(r=>['Resolved','Closed'].includes(r.status)).map(r=><ReportCard key={r.id} r={r} open={open}/>)}</div></section>}
 </main><footer><strong>⌖ FixMyArea</strong><p>Report it. Track it. Improve your community.</p><small>Public report locations reflect issue sites. Do not submit private personal information.</small></footer></>}
function ReportCard({r,open}:{r:Report;open:(r:Report)=>void}){return <button className="reportcard" onClick={()=>open(r)}><span className="badge">{r.status}</span><h3>{r.category}</h3><p>{r.community}</p><small>{r.tracking} · {new Date(r.created_at).toLocaleDateString()}</small></button>}
function DashboardReports({token,open}:{token:string;open:(r:Report)=>void}){const [items,setItems]=useState<Report[]>([]);useEffect(()=>{request('/api/organization/reports',{},token).then(setItems).catch(()=>{})},[token]);return <>{items.map(r=><ReportCard key={r.id} r={r} open={open}/>)}</>}
createRoot(document.getElementById('root')!).render(<App/>);
